package br.com.rjterapia.model.entity;

// Generated 19/02/2015 15:53:21 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Avaliacao generated by hbm2java
 */
@Entity
@Table(name = "avaliacao")
public class Avaliacao implements java.io.Serializable {

	private Integer id;
	private Cliente cliente;
	private Profissional profissional;
	private TipoAvaliacao tipoAvaliacao;
	private Date dtIncl;
	private String obs;
	private Integer pontos;

	public Avaliacao() {
	}

	public Avaliacao(Cliente cliente, Profissional profissional,
			TipoAvaliacao tipoAvaliacao) {
		this.cliente = cliente;
		this.profissional = profissional;
		this.tipoAvaliacao = tipoAvaliacao;
	}

	public Avaliacao(Cliente cliente, Profissional profissional,
			TipoAvaliacao tipoAvaliacao, Date dtIncl, String obs, Integer pontos) {
		this.cliente = cliente;
		this.profissional = profissional;
		this.tipoAvaliacao = tipoAvaliacao;
		this.dtIncl = dtIncl;
		this.obs = obs;
		this.pontos = pontos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cliente_id", nullable = false)
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "profissional_id", nullable = false)
	public Profissional getProfissional() {
		return this.profissional;
	}

	public void setProfissional(Profissional profissional) {
		this.profissional = profissional;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "tipo_avaliacao_id", nullable = false)
	public TipoAvaliacao getTipoAvaliacao() {
		return this.tipoAvaliacao;
	}

	public void setTipoAvaliacao(TipoAvaliacao tipoAvaliacao) {
		this.tipoAvaliacao = tipoAvaliacao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_incl", length = 19)
	public Date getDtIncl() {
		return this.dtIncl;
	}

	public void setDtIncl(Date dtIncl) {
		this.dtIncl = dtIncl;
	}

	@Column(name = "obs")
	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

	@Column(name = "pontos")
	public Integer getPontos() {
		return this.pontos;
	}

	public void setPontos(Integer pontos) {
		this.pontos = pontos;
	}

}
