package br.com.rjterapia.model.entity;

// Generated 19/02/2015 15:53:21 by Hibernate Tools 4.3.1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Clinica generated by hbm2java
 */
@Entity
@Table(name = "clinica")
public class Clinica implements java.io.Serializable {

	private Integer id;
	private String nome;
	private String descricao;
	private Date dtIncl;
	private Date dtAlter;
	private Date dtInat;
	private Set<Profissional> profissionals = new HashSet<Profissional>(0);

	public Clinica() {
	}

	public Clinica(String nome, String descricao, Date dtIncl) {
		this.nome = nome;
		this.descricao = descricao;
		this.dtIncl = dtIncl;
	}

	public Clinica(String nome, String descricao, Date dtIncl, Date dtAlter,
			Date dtInat, Set<Profissional> profissionals) {
		this.nome = nome;
		this.descricao = descricao;
		this.dtIncl = dtIncl;
		this.dtAlter = dtAlter;
		this.dtInat = dtInat;
		this.profissionals = profissionals;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", nullable = false, length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@Column(name = "descricao", nullable = false)
	public String getDescricao() {
		return this.descricao;
	}

	public void setDescricao(String descricao) {
		this.descricao = descricao;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_incl", nullable = false, length = 19)
	public Date getDtIncl() {
		return this.dtIncl;
	}

	public void setDtIncl(Date dtIncl) {
		this.dtIncl = dtIncl;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_alter", length = 19)
	public Date getDtAlter() {
		return this.dtAlter;
	}

	public void setDtAlter(Date dtAlter) {
		this.dtAlter = dtAlter;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_inat", length = 19)
	public Date getDtInat() {
		return this.dtInat;
	}

	public void setDtInat(Date dtInat) {
		this.dtInat = dtInat;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "clinica")
	public Set<Profissional> getProfissionals() {
		return this.profissionals;
	}

	public void setProfissionals(Set<Profissional> profissionals) {
		this.profissionals = profissionals;
	}

}
