package br.com.rjterapia.model.entity;

// Generated 19/02/2015 15:53:21 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * HistoricoPagamento generated by hbm2java
 */
@Entity
@Table(name = "historico_pagamento")
public class HistoricoPagamento implements java.io.Serializable {

	private Integer id;
	private Profissional profissional;
	private Date dtFimVigencia;
	private Date dtPagamento;
	private String obs;

	public HistoricoPagamento() {
	}

	public HistoricoPagamento(Profissional profissional, Date dtFimVigencia,
			Date dtPagamento) {
		this.profissional = profissional;
		this.dtFimVigencia = dtFimVigencia;
		this.dtPagamento = dtPagamento;
	}

	public HistoricoPagamento(Profissional profissional, Date dtFimVigencia,
			Date dtPagamento, String obs) {
		this.profissional = profissional;
		this.dtFimVigencia = dtFimVigencia;
		this.dtPagamento = dtPagamento;
		this.obs = obs;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "profissional_id", nullable = false)
	public Profissional getProfissional() {
		return this.profissional;
	}

	public void setProfissional(Profissional profissional) {
		this.profissional = profissional;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_fim_vigencia", nullable = false, length = 19)
	public Date getDtFimVigencia() {
		return this.dtFimVigencia;
	}

	public void setDtFimVigencia(Date dtFimVigencia) {
		this.dtFimVigencia = dtFimVigencia;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_pagamento", nullable = false, length = 19)
	public Date getDtPagamento() {
		return this.dtPagamento;
	}

	public void setDtPagamento(Date dtPagamento) {
		this.dtPagamento = dtPagamento;
	}

	@Column(name = "obs")
	public String getObs() {
		return this.obs;
	}

	public void setObs(String obs) {
		this.obs = obs;
	}

}
