package br.com.rjterapia.model.entity;

// Generated 19/02/2015 15:53:21 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Plano generated by hbm2java
 */
@Entity
@Table(name = "plano")
public class Plano implements java.io.Serializable {

	private Integer id;
	private String nome;
	private Set<Profissional> profissionals = new HashSet<Profissional>(0);

	public Plano() {
	}

	public Plano(String nome, Set<Profissional> profissionals) {
		this.nome = nome;
		this.profissionals = profissionals;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "plano")
	public Set<Profissional> getProfissionals() {
		return this.profissionals;
	}

	public void setProfissionals(Set<Profissional> profissionals) {
		this.profissionals = profissionals;
	}

}
