package br.com.rjterapia.model.entity;

// Generated 19/02/2015 15:53:21 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoAvaliacao generated by hbm2java
 */
@Entity
@Table(name = "tipo_avaliacao")
public class TipoAvaliacao implements java.io.Serializable {

	private Integer id;
	private String nome;
	private Set<Avaliacao> avaliacaos = new HashSet<Avaliacao>(0);

	public TipoAvaliacao() {
	}

	public TipoAvaliacao(String nome) {
		this.nome = nome;
	}

	public TipoAvaliacao(String nome, Set<Avaliacao> avaliacaos) {
		this.nome = nome;
		this.avaliacaos = avaliacaos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "nome", nullable = false, length = 45)
	public String getNome() {
		return this.nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoAvaliacao")
	public Set<Avaliacao> getAvaliacaos() {
		return this.avaliacaos;
	}

	public void setAvaliacaos(Set<Avaliacao> avaliacaos) {
		this.avaliacaos = avaliacaos;
	}

}
