package br.com.rjterapia.model.entity;

// Generated 19/02/2015 15:53:21 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Usuario generated by hbm2java
 */
@Entity
@Table(name = "usuario")
public class Usuario implements java.io.Serializable {

	private Integer id;
	private Cliente cliente;
	private Perfil perfil;
	private Profissional profissional;
	private Date dtAlter;
	private Date dtInat;
	private Date dtIncl;
	private String email;
	private String senha;

	public Usuario() {
	}

	public Usuario(Perfil perfil, Date dtIncl, String email, String senha) {
		this.perfil = perfil;
		this.dtIncl = dtIncl;
		this.email = email;
		this.senha = senha;
	}

	public Usuario(Cliente cliente, Perfil perfil, Profissional profissional,
			Date dtAlter, Date dtInat, Date dtIncl, String email, String senha) {
		this.cliente = cliente;
		this.perfil = perfil;
		this.profissional = profissional;
		this.dtAlter = dtAlter;
		this.dtInat = dtInat;
		this.dtIncl = dtIncl;
		this.email = email;
		this.senha = senha;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cliente_id")
	public Cliente getCliente() {
		return this.cliente;
	}

	public void setCliente(Cliente cliente) {
		this.cliente = cliente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "perfil_id", nullable = false)
	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "profissional_id")
	public Profissional getProfissional() {
		return this.profissional;
	}

	public void setProfissional(Profissional profissional) {
		this.profissional = profissional;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_alter", length = 19)
	public Date getDtAlter() {
		return this.dtAlter;
	}

	public void setDtAlter(Date dtAlter) {
		this.dtAlter = dtAlter;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_inat", length = 19)
	public Date getDtInat() {
		return this.dtInat;
	}

	public void setDtInat(Date dtInat) {
		this.dtInat = dtInat;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "dt_incl", nullable = false, length = 19)
	public Date getDtIncl() {
		return this.dtIncl;
	}

	public void setDtIncl(Date dtIncl) {
		this.dtIncl = dtIncl;
	}

	@Column(name = "email", nullable = false, length = 100)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "senha", nullable = false)
	public String getSenha() {
		return this.senha;
	}

	public void setSenha(String senha) {
		this.senha = senha;
	}
}