package br.com.rjterapia.model.entity;

// Generated 19/02/2015 15:53:21 by Hibernate Tools 4.3.1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Visualizacao generated by hbm2java
 */
@Entity
@Table(name = "visualizacao")
public class Visualizacao implements java.io.Serializable {

	private Integer id;
	private Profissional profissional;
	private Date dtVisualizacao;

	public Visualizacao() {
	}

	public Visualizacao(Profissional profissional) {
		this.profissional = profissional;
	}

	public Visualizacao(Profissional profissional, Date dtVisualizacao) {
		this.profissional = profissional;
		this.dtVisualizacao = dtVisualizacao;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "profissional_id", nullable = false)
	public Profissional getProfissional() {
		return this.profissional;
	}

	public void setProfissional(Profissional profissional) {
		this.profissional = profissional;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "dt_visualizacao", length = 10)
	public Date getDtVisualizacao() {
		return this.dtVisualizacao;
	}

	public void setDtVisualizacao(Date dtVisualizacao) {
		this.dtVisualizacao = dtVisualizacao;
	}

}
